version: '2'
# the latest tag is not pulling the latest image on Travis, so setting explicit
services:
  nifi:
    image: apache/nifi:1.9.1
    container_name: nifi
    hostname: nifi
    ports:
      - "8080:8080"
  registry:
    image: apache/nifi-registry:0.3.0
    container_name: registry
    hostname: registry
    ports:
      - "18080:18080"
